### ISSUE TITLE
Cambiar mensaje de bienvenida

### ISSUE THREAD

**Issue by LayneGranados** [LayneGranados/LugaresVP#49]
Cambiar el texto de la parte superior Derecha "Bienvenido Al Sistema Del Ventura Plaza" por "Bienvenido al Sistema de Inspección de Zonas del Centro Comercial Ventura Plaza"
![captura de pantalla 2016-02-22 a las 1 59 05 p m](https://cloud.githubusercontent.com/assets/362290/13228944/764c0498-d96c-11e5-988e-bdd358782989.png)

**Comment by axidsugar** [comment]
Se Cierrra el issue con el Pull Request #52
